### ISSUE TITLE
drush si is broken 

### ISSUE THREAD

**Issue by martinfrances107** [socketwench/dropwhale#31]
Recently there have been changes to drush which I have had to take into account in my own personal development scripts ...  I am finding I need to make the same change to dropwhale

I get a consistent fail - When running .dropwhale.sh

The failing task in  .dropwhale/web/ansible/reset.yml 

In the "Install drupal" task I will leave the debug out at the bottom of this issue.

In short the solution is to add an additional switch the site install command 

drush si --uri=http://web --root=/var/www/html --db-url=mysql://drupal:drupal@db/drupal -y --account-name=admin --account-pass=password

I find I need to add **--sites-subdir=http://web**

I will post a pull request soon....

TASK [Install drupal] **********************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "drush si --uri=http://web --root=/var/www/html --db-url=mysql://drupal:drupal@db/drupal -y --account-name=admin --account-pass=password", "delta": "0:00:01.510440", "end": "2017-11-20 13:13:21.639210", "failed": true, "rc": 1, "start": "2017-11-20 13:13:20.128770", "stderr": " [error]  Could not determine target sites directory for site to install. Use --site-subdir to specify. ", "stderr_lines": [" [error]  Could not determine target sites directory for site to install. Use --site-subdir to specify. "], "stdout": "", "stdout_lines": []}

**Comment by martinfrances107** [comment]
I have posted a fix which works for me.

**Comment by socketwench** [comment]
Is *that* why Drush beta 9 breaks things? Huh.

**Comment by martinfrances107** [comment]
Is that why Drush beta 9 breaks things?

Ah I was experiencing problems  on beta 4.

I do have a unease .. what could be difference from your setup  and  mine .... I wish had a more definitive explanation.

**Comment by martinfrances107** [comment]
>I wish had a more definitive explanation.

Me too ... At the time drush was a little flakey. Recently drush seems more stable. I think this issue can be closed.
